#!/bin/sh

# Cooldown period in seconds
COOLDOWN=1
STATE_FILE="/tmp/volume_control_state"

# Initialize the state file if it doesn't exist
if [ ! -f "$STATE_FILE" ]; then
    echo 0 > "$STATE_FILE"
fi

last_action=$(cat "$STATE_FILE")

down() {
    current_time=$(date +%s.%N)
    pamixer -d 2
    if (( $(echo "$current_time - $last_action >= $COOLDOWN" | bc -l) )); then 
        volume=$(pamixer --get-volume)
        [ $volume -gt 0 ] && volume=$(expr $volume)

        dunstify -a "VOLUME" "Decreasing to $volume%" -h int:value:"$volume" -i audio-volume-low-symbolic -r 2593 -u normal
        canberra-gtk-play -i audio-volume-change -d "changevolume"

        echo "$current_time" > "$STATE_FILE"  # Update last action time
    fi
}

up() {
    current_time=$(date +%s.%N)
    pamixer -i 2
    if (( $(echo "$current_time - $last_action >= $COOLDOWN" | bc -l) )); then
        volume=$(pamixer --get-volume)
        [ $volume -lt 100 ] && volume=$(expr $volume)

        dunstify -a "VOLUME" "Increasing to $volume%" -h int:value:"$volume" -i audio-volume-high-symbolic -r 2593 -u normal
        canberra-gtk-play -i audio-volume-change -d "changevolume"

        echo "$current_time" > "$STATE_FILE"  # Update last action time
    fi
}

mute() {
    muted="$(pamixer --get-mute)"
    if $muted; then
        pamixer -u
        dunstify -a "VOLUME" "UNMUTED" -i audio-volume-high-symbolic -r 2593 -u normal
    else 
        pamixer -m
        dunstify -a "VOLUME" "MUTED" -i audio-volume-muted-symbolic -r 2593 -u normal
    fi
}

case "$1" in
    up) up;;
    down) down;;
    mute) mute;;
esac
